apiVersion: v1
kind: Pod
metadata:
  name: app-kuber
  namespace: app
spec:
  serviceAccountName: kuber-sa
  containers:
  - name: app-kuber-container
    image: roflmaoinmysoul/otus:v2.0
    ports:
    - containerPort: 8000