apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app
  name: kuber-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "patch"]